--liquibase formatted sql
--changeset tuanha2:1.2
CREATE TABLE device_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  name longvarchar,
  product_class longvarchar,
  manufacturer longvarchar,
  oui longvarchar,
  created bigint,
  updated bigint,
  connection_request_username longvarchar,
  connection_request_password longvarchar,
  interval_time bigint,
  model_name longvarchar
)

CREATE TABLE tags (
  id  bigint GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  created bigint,
  updated bigint,
  name longvarchar,
  parameters longvarchar,
  assigned bigint,
  type longvarchar,
  device_type_version_id bigint,
  assigned_group bigint,
  parent_object longvarchar,
  root_tag_id bigint,
  corresponding_module longvarchar
)

create table device_type_versions (
  id bigint GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  device_type_id bigint,
  firmware_version longvarchar,
  data_model_file_name longvarchar,
  firmware_file_name longvarchar,
  firmware_file_id longvarchar,
  parameters longvarchar,
  created bigint,
  updated bigint,
  diagnostics longvarchar,
  manufacturer longvarchar,
  name longvarchar,
  model_name longvarchar,
  oui longvarchar,
  product_class longvarchar
)

CREATE TABLE policy_jobs(
  id bigint,
  status longvarchar,
  device_group_id bigint,
  external_devices longvarchar,
  external_filename longvarchar,
  start_at bigint,
  time_interval bigint,
  max_number bigint,
  events longvarchar,
  is_immediately bigint,
  action_name longvarchar,
  parameters longvarchar,
  preset_id longvarchar,
  created bigint,
  updated bigint,
  name longvarchar
)
