--liquibase formatted sql
--changeset thanhlx:1.45
DROP TABLE IF EXISTS `area_groups`;
ALTER TABLE `blacklist_devices` CHANGE `device_id` `device_id` VARCHAR(1024);
ALTER TABLE `device_groups` CHANGE `name` `name` VARCHAR(1024);
ALTER TABLE `device_groups` CHANGE `manufacturer` `manufacturer` VARCHAR(256);
ALTER TABLE `device_groups` CHANGE `model_name` `model_name` VARCHAR(256);
ALTER TABLE `device_groups` CHANGE `firmware_version` `firmware_version` VARCHAR(256);
ALTER TABLE `device_groups` CHANGE `label` `label` TEXT;
ALTER TABLE `device_types` CHANGE `name` `name` VARCHAR(1024);
ALTER TABLE `device_types` CHANGE `product_class` `product_class` VARCHAR(256);
ALTER TABLE `device_types` CHANGE `manufacturer` `manufacturer` VARCHAR(256);
ALTER TABLE `device_types` CHANGE `oui` `oui` VARCHAR(256);
ALTER TABLE `device_types` CHANGE `model_name` `model_name` VARCHAR(256);
ALTER TABLE `device_types` DROP COLUMN `connection_request_username`;
ALTER TABLE `device_types` DROP COLUMN `connection_request_password`;
ALTER TABLE `device_types` DROP COLUMN `interval_time`;
ALTER TABLE `device_type_versions` DROP COLUMN `data_model_file_name`;
ALTER TABLE `device_type_versions` DROP COLUMN `firmware_file_name`;
ALTER TABLE `device_type_versions` DROP COLUMN `firmware_file_id`;
ALTER TABLE `device_type_versions` CHANGE `firmware_version` `firmware_version` VARCHAR(256);
ALTER TABLE `device_type_versions` CHANGE `manufacturer` `manufacturer` VARCHAR(256);
ALTER TABLE `device_type_versions` CHANGE `oui` `oui` VARCHAR(256);
ALTER TABLE `device_type_versions` CHANGE `product_class` `product_class` VARCHAR(256);
ALTER TABLE `device_type_versions` CHANGE `model_name` `model_name` VARCHAR(256);
ALTER TABLE `device_type_versions` CHANGE `parameters` `parameters` LONGTEXT;
ALTER TABLE `device_type_versions` CHANGE `diagnostics` `diagnostics` LONGTEXT;
ALTER TABLE `diagnostic_tasks` CHANGE `device_id` `device_id` VARCHAR(1024);
ALTER TABLE `diagnostic_tasks` CHANGE `diagnostics_name` `diagnostics_name` VARCHAR(1024);
ALTER TABLE `diagnostic_tasks` CHANGE `result` `result` MEDIUMTEXT;
ALTER TABLE `diagnostic_tasks` CHANGE `status` `status` TINYINT(2);
ALTER TABLE `diagnostic_tasks` CHANGE `done` `completed` BIGINT(20);
ALTER TABLE `diagnostic_tasks` CHANGE `task_id` `task_id` VARCHAR(256);
DROP TABLE IF EXISTS `filters`;
DROP TABLE IF EXISTS `firmware_tasks`;
ALTER TABLE `parameter_details` CHANGE `path` `path` VARCHAR(1024);
ALTER TABLE `parameter_details` CHANGE `tr069_name` `tr069_name` VARCHAR(1024);
ALTER TABLE `parameter_details` CHANGE `short_name` `short_name` VARCHAR(1024);
ALTER TABLE `parameter_details` CHANGE `data_type` `data_type` VARCHAR(64);
ALTER TABLE `parameter_details` CHANGE `rule` `rule` TEXT;
ALTER TABLE `parameter_details` CHANGE `parent_object` `parent_object` VARCHAR(1024);
ALTER TABLE `parameter_details` CHANGE `version` `version` VARCHAR(8);
ALTER TABLE `parameter_details` CHANGE `profile` `profile` VARCHAR(64);
ALTER TABLE `parameter_details` CHANGE `access` `access` VARCHAR(8);
ALTER TABLE `parameter_details` CHANGE `tr069_parent_object` `tr069_parent_object` VARCHAR(1024);
ALTER TABLE `policy_jobs` CHANGE `status` `status` VARCHAR(8);
ALTER TABLE `policy_jobs` CHANGE `external_filename` `external_filename` VARCHAR(1024);
ALTER TABLE `policy_jobs` CHANGE `events` `events` VARCHAR(1024);
ALTER TABLE `policy_jobs` CHANGE `is_immediately` `is_immediately` TINYINT(1);
ALTER TABLE `policy_jobs` CHANGE `action_name` `action_name` VARCHAR(64);
ALTER TABLE `policy_jobs` CHANGE `parameters` `parameters` TEXT;
ALTER TABLE `policy_jobs` CHANGE `preset_id` `preset_id` VARCHAR(32);
ALTER TABLE `policy_jobs` CHANGE `name` `name` VARCHAR(1024);
ALTER TABLE `policy_tasks` CHANGE `done` `completed` BIGINT(20);
ALTER TABLE `policy_tasks` CHANGE `task_id` `task_id` VARCHAR(256);
ALTER TABLE `subscribers` CHANGE `subscriber_id` `subscriber_id` VARCHAR(1024);
ALTER TABLE `subscribers` CHANGE `subscriber_data_template_ids` `subscriber_data_template_ids` VARCHAR(256);
ALTER TABLE `subscriber_devices` CHANGE `subscriber_id` `subscriber_id` VARCHAR(1024);
ALTER TABLE `subscriber_devices` CHANGE `device_id` `device_id` VARCHAR(1024);
ALTER TABLE `subscriber_devices` CHANGE `manufacturer` `manufacturer` VARCHAR(256);
ALTER TABLE `subscriber_devices` CHANGE `oui` `oui` VARCHAR(256);
ALTER TABLE `subscriber_devices` CHANGE `product_class` `product_class` VARCHAR(256);
ALTER TABLE `subscriber_devices` CHANGE `serial_number` `serial_number` VARCHAR(256);
ALTER TABLE `subscriber_templates` CHANGE `name` `name` VARCHAR(1024);
ALTER TABLE `tags` CHANGE `name` `name` VARCHAR(1024);
ALTER TABLE `tags` CHANGE `assigned` `assigned` TINYINT(1);
ALTER TABLE `tags` CHANGE `assigned_group` `assigned_group` VARCHAR(16);
ALTER TABLE `tags` DROP COLUMN `type`;
TRUNCATE `tr069_parameters`;
ALTER TABLE `tr069_parameters` DROP PRIMARY KEY;
ALTER TABLE `tr069_parameters` ADD PRIMARY KEY(`id`);
ALTER TABLE `tr069_parameters` MODIFY `id` BIGINT(20) NOT NULL AUTO_INCREMENT;
ALTER TABLE `tr069_parameters` CHANGE `path` `path` VARCHAR(256);
ALTER TABLE `tr069_parameters` CHANGE `data_type` `data_type` VARCHAR(64);
ALTER TABLE `tr069_parameters` CHANGE `parent_object` `parent_object` VARCHAR(1024);
ALTER TABLE `tr069_parameters` CHANGE `version` `version` VARCHAR(8);
ALTER TABLE `tr069_parameters` CHANGE `access` `access` VARCHAR(8);
TRUNCATE `tr069_profiles`;
ALTER TABLE `tr069_profiles` DROP PRIMARY KEY;
ALTER TABLE `tr069_profiles` ADD PRIMARY KEY(`id`);
ALTER TABLE `tr069_profiles` MODIFY `id` BIGINT(20) NOT NULL AUTO_INCREMENT;
ALTER TABLE `tr069_profiles` CHANGE `name` `name` VARCHAR(256);
ALTER TABLE `tr069_profiles` CHANGE `version` `version` VARCHAR(8);
